    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.partner.NazionePrimrose', 'it.dnd.thip.base.partner.YNazionePrimrose', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.partner.NazionePrimroseTM', 'it.dnd.thip.base.partner.YNazionePrimroseTM', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('Nazione', 'YNazionePrimrose', '1', 'Y', 'N');
